name: 'Setup Java'
description: |
  Configure Java environment for builds. Extends actions/setup-java to include Fortnox Nexus repository settings.
inputs:
  java-version:
    description: 'Java version to set up'
    default: "21"
  cache:
    description: 'Name of the build platform to cache dependencies. It can be "maven", "gradle" or "sbt".'
    required: false
  nexus-deploy-password:
    description: 'Password for the Nexus deployment user. This is required if you want to deploy to the internal Nexus repository.'
    default: ''
    required: false

runs:
  using: "composite"

  steps:
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: "${{ inputs.java-version }}"
        distribution: 'temurin'
        cache: ${{ inputs.cache }}
        server-id: github
        # settings-path: ${{ github.workspace }}

    # These extra settings are needed to be able to use the Fortnox Nexus repository
    - uses: s4u/maven-settings-action@v3.1.0
      with:
        mirrors: |
          [
            {"id": "nexus", "name": "nexus", "mirrorOf": "*", "url": "https://nexus.fnox.se/nexus/content/groups/public"}
          ]
        repositories: |
          [
            {"id":"central","url":"http://central","snapshots":{"enabled":true},"releases":{"enabled":true}}
          ]
#        servers: |
#          [
#            {"id": "nexus", "name": "nexus", "username": "deployment", "password": "${{ inputs.nexus-deploy-password }}"}
#          ]

