name: 'Deploy'
description: 'Deploy to an environment'
inputs:
  environment:
    description: 'Environment to deploy to'
    required: true
  block_message:
    description: 'Deploy block message or false to allow deploys'
    required: true
  tag:
    description: 'Tag to deploy'
    required: true

runs:
  using: "composite"

  steps:
    - name: Install prerequisites
      shell: bash
      run: |
        set -x
        echo Install fnxctl
        #curl -o fnxctl https://fnxctl.fnox.se/fnxctl-linux-amd64 && chmod +x fnxctl && sudo mv fnxctl /usr/local/bin/fnxctl
    - name: Deploy to ${{ inputs.environment }}
      shell: bash
      run: |
        echo "Deploying tag ${{ inputs.tag }} to environment ${{ inputs.environment }}"
        #fnxctl deploy --method=gitops --env=${{ inputs.environment }} ${{ inputs.tag }}
        echo "Deployment of ${{ inputs.tag }} to ${{ inputs.environment }} completed"
        
        # This replicates the Jenkins setDeployed call
        echo "Setting deployment status for ${{ inputs.tag }} in ${{ inputs.environment }} environment"

