name: Deploy

on:
  repository_dispatch:
    types: [version_created]
  workflow_dispatch:
    inputs:
        tag:
          description: 'Tag to deploy'
          required: true

permissions:
  contents: read
  #checks: write # JUnit reports
  #pull-requests: write # JUnit reports
  #packages: write
  #actions: write
  #attestations: write # Required for the Docker build-push-action to work
  #id-token: write # Required for the Docker build-push-action to work

env:
  REGISTRY: ghcr.io
  # IMAGE_NAME: ${{ github.repository_owner }}/${{ github.event.repository.name }}
  MAVEN_ARGS: "--batch-mode --no-transfer-progress"

jobs:
  # Steps that do not require a build, such as linting the catalog-info.yaml file
  deploy-dev:
    name: Deploy to development environment
    runs-on: "${{ vars.DEFAULT_RUNNER }}"
    env:
      DEPLOY_TAG: ${{
        if(github.event_name == 'workflow_dispatch',
          github.event.inputs.tag, # True: Use workflow_dispatch input
          if(github.event_name == 'repository_dispatch',
            fromJson(github.event.client_payload).tag, # True: Safely parse client_payload
            'latest' # False: Default fallback
          )
        )
      }}
    steps:
      - name: Use Parsed Properties
        run: |
          echo "Preparing deployment for ${{ env.DEPLOY_TAG }}"
