name: Deploy

on:
  push:
    branches:
      - "master"
  workflow_dispatch: {}

permissions:
  contents: read
  #checks: write # JUnit reports
  #pull-requests: write # JUnit reports
  #packages: write
  #actions: write
  #attestations: write # Required for the Docker build-push-action to work
  #id-token: write # Required for the Docker build-push-action to work

env:
  REGISTRY: ghcr.io
  # IMAGE_NAME: ${{ github.repository_owner }}/${{ github.event.repository.name }}
  MAVEN_ARGS: "--batch-mode --no-transfer-progress"

jobs:
  # Steps that do not require a build, such as linting the catalog-info.yaml file
  test:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Test
        run: |
          echo Test
