name: PR Build

on:
  # 1. Manual Dispatch
  workflow_dispatch: { }

  # 2. Pull Request Commit Push
  pull_request:
    # Triggers only when commits are pushed to the PR
    types: [ opened, synchronize ]
    # Restrict to specific branches (e.g., 'main', 'develop')
    branches:
      - 'master'

permissions:
  contents: read
  checks: write # JUnit reports
  pull-requests: write # JUnit reports
  #packages: write
  #actions: write
  #attestations: write # Required for the Docker build-push-action to work
  #id-token: write # Required for the Docker build-push-action to work

env:
  REGISTRY: ghcr.io
  # IMAGE_NAME: ${{ github.repository_owner }}/${{ github.event.repository.name }}
  MAVEN_ARGS: "--batch-mode --no-transfer-progress"

jobs:
  merge-check:
    name: Merge Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check if merges are allowed
        uses: ./.github/actions/merge-check-action
        with:
          message: "${{ vars.MERGE_BLOCK_MESSAGE }}"

  # Steps that do not require a build, such as linting the catalog-info.yaml file
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Backstage Entity
        uses: RoadieHQ/backstage-entity-validator@v0.5.0
        with:
          path: 'catalog-info.yaml'

  # The build job that compiles the code, runs tests, and generates reports
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: ./.github/actions/setup-java-action
        with:
          java-version: "21"

      - name: Test
        run: |
          ./mvnw ${{ env.MAVEN_ARGS }} clean verify --file pom.xml

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v5
        if: success() || failure()

        with:
          check_name: |
            JUnit Test Report
            Cucumber Test Report
          report_paths: |
            **/target/surefire-reports/TEST-*.xml
          include_passed: true
          include_time_in_summary: true

